# Generated by Django 5.0

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "app_id",
                    models.UUIDField(
                        db_column="app_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_secret", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_apps",
                        to="api.User",
                    ),
                ),
            ],
            options={
                "db_table": "api_app",
                "ordering": ["-created_at"],
            },
        ),
    ]
