# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jti", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to="api.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to="api.User",
                    ),
                ),
            ],
            options={
                "db_table": "api_one_time_token",
            },
        ),
        migrations.AddConstraint(
            model_name="onetimetoken",
            constraint=models.UniqueConstraint(
                name="api_one_time_token_one_per_user_app",
                fields=("user", "app"),
            ),
        ),
    ]
