# Generated by Django 5.0

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_one_time_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "server_id",
                    models.UUIDField(
                        db_column="server_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("server_name", models.CharField(max_length=255)),
                ("server_description", models.TextField(blank=True)),
                ("game_modes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servers",
                        to="api.app",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_servers",
                        to="api.User",
                    ),
                ),
            ],
            options={
                "db_table": "api_server",
                "ordering": ["-created_at"],
            },
        ),
    ]
