# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_server_created_by_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
