# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_server_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="game_frontend_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
