FROM node:22-alpine AS build
WORKDIR /app

COPY tower-defense-frontend/package.json tower-defense-frontend/package-lock.json* ./
ENV NODE_ENV=
RUN npm install

COPY tower-defense-frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY tower-defense-frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
