version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            game-backend/.* game-backend true
            game-frontend/.* game-frontend true
            tower-defense-backend/.* tower-defense-backend true
            tower-defense-frontend/.* tower-defense-frontend true
            matchmaker-backend/.* matchmaker-backend true
            matchmaker-frontend/.* matchmaker-frontend true
            discord-bot/.* discord-bot true
          base-revision: main
          config-path: .circleci/continue_config.yml
