# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_servers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
