# Generated by Django 5.0

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_server_game_frontend_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="LFGGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(db_index=True, max_length=32)),
                ("start_time", models.DateTimeField()),
                ("duration", models.FloatField()),
                ("max_party_size", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=2048)),
            ],
            options={
                "db_table": "api_lfg_group",
                "ordering": ["-created_at"],
            },
        ),
    ]
