# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_lfg_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="LFGMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("discord_id", models.CharField(db_index=True, max_length=32)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lfg",
                    models.ForeignKey(
                        db_column="lfg_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.lfggroup",
                    ),
                ),
            ],
            options={
                "db_table": "api_lfg_member",
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="lfgmember",
            constraint=models.UniqueConstraint(
                fields=("lfg", "discord_id"),
                name="api_lfg_member_unique_lfg_discord",
            ),
        ),
    ]
